name: BBFN
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - autopep8=1.4.4=py_0
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - ca-certificates=2020.10.14=0
  - catalogue=0.0.8=py_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.13.2=py37h8022711_0
  - chardet=3.0.4=py37he5f6b98_1008
  - colorama=0.4.4=py_0
  - cryptography=2.8=py37hb09aad4_2
  - cudatoolkit=10.1.243=h6bb024c_0
  - cymem=2.0.3=py37h3340039_3
  - freetype=2.10.0=he06d7ca_2
  - idna=2.8=py37_1000
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=243
  - jpeg=9c=h14c3975_1001
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_5
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libwebp-base=1.1.0=h516909a_3
  - lz4-c=1.8.3=he1b5a44_1001
  - mkl=2019.4=243
  - more-itertools=7.2.0=py_0
  - murmurhash=1.0.0=py37h3340039_1
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.9.0=hc9558a2_1
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1h=h7b6447c_0
  - pillow=6.2.1=py37hd70f55b_1
  - pip=19.3.1=py37_0
  - plac=0.9.6=py_1
  - pycodestyle=2.5.0=py_0
  - pycparser=2.19=py_2
  - pyopenssl=19.0.0=py37_0
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.5=h0371630_0
  - python_abi=3.7=1_cp37m
  - readline=7.0=hf8c457e_1001
  - requests=2.22.0=py37_1
  - setuptools=42.0.1=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - srsly=0.2.0=py37he1b5a44_0
  - tk=8.6.10=hed695b0_1
  - torchvision=0.4.2=py37_cu101
  - wasabi=0.4.0=py_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h516909a_1002
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.4=h3b9ef0a_2
  - pip:
    - absl-py==0.8.1
    - alabaster==0.7.12
    - allennlp==0.9.0
    - argparse==1.4.0
    - astor==0.8.0
    - astroid==2.3.3
    - astropy==4.2
    - astunparse==1.6.3
    - atomicwrites==1.3.0
    - babel==2.7.0
    - backcall==0.1.0
    - bleach==3.1.0
    - blis==0.2.4
    - boto==2.49.0
    - boto3==1.10.14
    - botocore==1.13.14
    - cachetools==3.1.1
    - click==7.0
    - conllu==1.3.1
    - csdmpy==0.3.5
    - cycler==0.10.0
    - dataclasses==0.6
    - decorator==4.4.1
    - defusedxml==0.6.0
    - docopt==0.6.2
    - docutils==0.15.2
    - editdistance==0.5.3
    - entrypoints==0.3
    - filelock==3.0.12
    - flaky==3.6.1
    - flask==1.1.1
    - flask-cors==3.0.8
    - ftfy==5.6
    - future==0.18.2
    - gast==0.3.3
    - gensim==3.8.1
    - gevent==1.4.0
    - google-auth==1.7.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - googledrivedownloader==0.4
    - greenlet==0.4.15
    - grpcio==1.25.0
    - h5py==2.10.0
    - imageio==2.6.1
    - imagesize==1.1.0
    - ipdb==0.13.4
    - ipykernel==5.1.3
    - ipython==7.9.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - isodate==0.6.0
    - isort==4.3.21
    - itsdangerous==1.1.0
    - jedi==0.15.1
    - jinja2==2.10.3
    - jmespath==0.9.4
    - joblib==0.14.0
    - json-lines==0.5.0
    - jsonlines==1.2.0
    - jsonnet==0.14.0
    - jsonpickle==1.2
    - jsonschema==3.1.1
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.1.0
    - lazy-object-proxy==1.4.3
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - mccabe==0.6.1
    - mistune==0.8.4
    - monotonic==1.5
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - networkx==2.4
    - nltk==3.4.5
    - notebook==6.0.2
    - numexpr==2.7.1
    - numpy==1.18.5
    - numpydoc==0.9.1
    - oauthlib==3.1.0
    - opencv-python==4.1.1.26
    - opt-einsum==3.1.0
    - overrides==2.5
    - packaging==19.2
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - parsimonious==0.8.1
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pipreqs==0.4.10
    - pluggy==0.13.0
    - plyfile==0.7.1
    - preshed==2.0.1
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - protobuf==3.10.0
    - ptyprocess==0.6.0
    - py==1.8.0
    - pyasn1==0.4.7
    - pyasn1-modules==0.2.7
    - pyconll==2.2.1
    - pyerfa==1.7.1.1
    - pygments==2.4.2
    - pylint==2.4.3
    - pyparsing==2.4.5
    - pyrsistent==0.15.5
    - pytest==5.2.2
    - python-dateutil==2.8.0
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pytz==2019.3
    - pywavelets==1.1.1
    - pyzmq==18.1.0
    - qtconsole==4.5.5
    - rdflib==4.2.2
    - regex==2019.11.1
    - requests-oauthlib==1.3.0
    - responses==0.10.7
    - rsa==4.0
    - s3transfer==0.2.1
    - sacremoses==0.0.35
    - scikit-image==0.16.2
    - scikit-learn==0.21.3
    - scipy==1.3.2
    - send2trash==1.5.0
    - sentencepiece==0.1.83
    - smart-open==1.9.0
    - snowballstemmer==2.0.0
    - spacy==2.1.9
    - sphinx==2.2.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - sqlparse==0.3.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==1.9
    - tensorflow-estimator==2.3.0
    - tensorflow-gpu==2.3.1
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.4
    - thinc==7.0.8
    - tokenizers==0.9.4
    - torch==1.7.0
    - torch-cluster==1.4.5
    - torch-geometric==1.3.2
    - torch-scatter==1.4.0
    - torch-sparse==0.4.3
    - torch-spline-conv==1.1.1
    - tornado==6.0.3
    - tqdm==4.38.0
    - traitlets==4.3.3
    - transformers==4.0.0
    - typed-ast==1.4.0
    - typing-extensions==3.7.4.3
    - unidecode==1.1.1
    - urllib3==1.25.6
    - validators==0.14.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.16.0
    - widgetsnbextension==3.5.1
    - word2number==1.1
    - wrapt==1.11.1
    - yarg==0.1.9
prefix: /home/henry/miniconda3/envs/BBFN

